# Generated by Django 5.1.4 on 2026-04-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_threads', to='agent.productcard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=2000)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_source_type', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram Reel'), ('tiktok', 'TikTok'), ('upload', 'Uploaded File'), ('image', 'Image URL'), ('other', 'Other URL')], default='other', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('extracted_product_name', models.CharField(blank=True, max_length=300)),
                ('extracted_brand', models.CharField(blank=True, max_length=100)),
                ('extracted_category', models.CharField(blank=True, max_length=100)),
                ('extracted_specs', models.JSONField(default=list)),
                ('extracted_price_hint', models.CharField(blank=True, max_length=100)),
                ('video_type', models.CharField(choices=[('review', 'Review'), ('unboxing', 'Unboxing'), ('advertisement', 'Advertisement'), ('tutorial', 'Tutorial'), ('other', 'Other')], default='other', max_length=20)),
                ('video_summary', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('raw_gemini_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_analyses', to='agent.productcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='agent.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
