"""
Dummy product catalog — 20 products across 7 categories.
Used as the primary search source; also bundled as fixtures.
"""

DUMMY_CATALOG = [
    # ── EARBUDS ──────────────────────────────────────────────────────────────
    {
        "id": 1,
        "name": "boAt Airdopes 141",
        "brand": "boAt",
        "category": "earbuds",
        "price": 1299,
        "currency": "INR",
        "rating": 4.1,
        "review_count": 124000,
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B09BZ3KP7S",
        "specs": {
            "driver": "8mm",
            "battery_total": "42h",
            "battery_earbuds": "6h",
            "water_resistance": "IPX4",
            "connectivity": "Bluetooth 5.1",
            "mic": "Yes",
        },
        "keywords": ["earbuds", "boat", "budget", "wireless", "tws", "cheap"],
    },
    {
        "id": 2,
        "name": "Realme Buds T100",
        "brand": "Realme",
        "category": "earbuds",
        "price": 1799,
        "currency": "INR",
        "rating": 4.0,
        "review_count": 45000,
        "image_url": "https://images.unsplash.com/photo-1631176093617-8a8ba69e7a14?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0BSGQ953C",
        "specs": {
            "driver": "10mm",
            "battery_total": "28h",
            "battery_earbuds": "7h",
            "water_resistance": "IPX5",
            "connectivity": "Bluetooth 5.3",
            "anc": "Basic noise reduction",
        },
        "keywords": ["earbuds", "realme", "budget", "wireless", "tws"],
    },
    {
        "id": 3,
        "name": "Sony WF-C500",
        "brand": "Sony",
        "category": "earbuds",
        "price": 3990,
        "currency": "INR",
        "rating": 4.4,
        "review_count": 32000,
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B09BQDGKRP",
        "specs": {
            "driver": "6mm",
            "battery_total": "20h",
            "battery_earbuds": "10h",
            "water_resistance": "IPX4",
            "connectivity": "Bluetooth 5.0",
            "sound_tech": "360 Reality Audio",
        },
        "keywords": ["earbuds", "sony", "premium", "wireless", "tws", "quality"],
    },
    # ── HEADPHONES ───────────────────────────────────────────────────────────
    {
        "id": 4,
        "name": "boAt Rockerz 450",
        "brand": "boAt",
        "category": "headphones",
        "price": 1499,
        "currency": "INR",
        "rating": 4.0,
        "review_count": 89000,
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B07WLKP3MS",
        "specs": {
            "driver": "40mm",
            "battery": "15h",
            "charging": "Micro USB",
            "connectivity": "Bluetooth 5.0",
            "type": "Over-ear",
        },
        "keywords": ["headphones", "boat", "over-ear", "budget", "wireless"],
    },
    {
        "id": 5,
        "name": "JBL Tune 510BT",
        "brand": "JBL",
        "category": "headphones",
        "price": 2999,
        "currency": "INR",
        "rating": 4.3,
        "review_count": 56000,
        "image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B08WMJXHRS",
        "specs": {
            "driver": "40mm",
            "battery": "40h",
            "charging": "USB-C",
            "connectivity": "Bluetooth 5.0",
            "type": "On-ear, foldable",
            "multipoint": "Yes",
        },
        "keywords": ["headphones", "jbl", "on-ear", "foldable", "wireless", "long battery"],
    },
    # ── LAPTOPS ──────────────────────────────────────────────────────────────
    {
        "id": 6,
        "name": "Lenovo IdeaPad Slim 3",
        "brand": "Lenovo",
        "category": "laptops",
        "price": 41990,
        "currency": "INR",
        "rating": 4.2,
        "review_count": 18000,
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0CW13XG4Y",
        "specs": {
            "processor": "AMD Ryzen 5 7520U",
            "ram": "8GB DDR5",
            "storage": "512GB SSD",
            "display": "15.6\" FHD IPS",
            "battery": "45Wh",
            "os": "Windows 11 Home",
            "weight": "1.62kg",
        },
        "keywords": ["laptop", "lenovo", "ideapad", "budget", "coding", "student", "ryzen"],
    },
    {
        "id": 7,
        "name": "Acer Aspire Lite",
        "brand": "Acer",
        "category": "laptops",
        "price": 37990,
        "currency": "INR",
        "rating": 4.0,
        "review_count": 9000,
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0BT2DW4NH",
        "specs": {
            "processor": "Intel Core i3-1215U",
            "ram": "8GB DDR4",
            "storage": "256GB SSD",
            "display": "15.6\" FHD IPS",
            "battery": "56Wh",
            "os": "Windows 11 Home",
            "weight": "1.65kg",
        },
        "keywords": ["laptop", "acer", "aspire", "budget", "cheap", "student"],
    },
    {
        "id": 8,
        "name": "HP Laptop 15s",
        "brand": "HP",
        "category": "laptops",
        "price": 45990,
        "currency": "INR",
        "rating": 4.3,
        "review_count": 22000,
        "image_url": "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0BWPXM73X",
        "specs": {
            "processor": "Intel Core i5-1235U",
            "ram": "8GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD Anti-glare",
            "battery": "41Wh",
            "os": "Windows 11 Home",
            "weight": "1.75kg",
        },
        "keywords": ["laptop", "hp", "corei5", "mid-range", "office", "coding"],
    },
    {
        "id": 9,
        "name": "Asus VivoBook 15",
        "brand": "Asus",
        "category": "laptops",
        "price": 49990,
        "currency": "INR",
        "rating": 4.4,
        "review_count": 14000,
        "image_url": "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0C1KCX9GM",
        "specs": {
            "processor": "AMD Ryzen 7 5800H",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD 144Hz",
            "battery": "50Wh",
            "os": "Windows 11 Home",
            "weight": "1.8kg",
        },
        "keywords": ["laptop", "asus", "vivobook", "ryzen7", "gaming", "16gb", "performance"],
    },
    # ── AIR FRYERS ───────────────────────────────────────────────────────────
    {
        "id": 10,
        "name": "Instant Vortex Plus 6-in-1",
        "brand": "Instant",
        "category": "air_fryers",
        "price": 7999,
        "currency": "INR",
        "rating": 4.5,
        "review_count": 8700,
        "image_url": "https://images.unsplash.com/photo-1648146342293-36e8a81a7ac9?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B08CQHKKPJ",
        "specs": {
            "capacity": "5.7L",
            "wattage": "1500W",
            "functions": "6-in-1 (Air Fry, Roast, Bake, Broil, Reheat, Dehydrate)",
            "display": "Digital touch",
            "warranty": "1 year",
        },
        "keywords": ["air fryer", "instant", "large", "family", "6in1", "digital"],
    },
    {
        "id": 11,
        "name": "Philips HD9200/90",
        "brand": "Philips",
        "category": "air_fryers",
        "price": 5495,
        "currency": "INR",
        "rating": 4.3,
        "review_count": 15000,
        "image_url": "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B08LCWGH65",
        "specs": {
            "capacity": "4.1L",
            "wattage": "1400W",
            "technology": "Rapid Air",
            "display": "Manual knob",
            "warranty": "2 years",
        },
        "keywords": ["air fryer", "philips", "rapid air", "mid", "2year warranty"],
    },
    {
        "id": 12,
        "name": "Havells Prolife Digi",
        "brand": "Havells",
        "category": "air_fryers",
        "price": 4199,
        "currency": "INR",
        "rating": 4.0,
        "review_count": 6200,
        "image_url": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B08X8XQVTM",
        "specs": {
            "capacity": "4L",
            "wattage": "1230W",
            "display": "Digital LED",
            "temperature_range": "80–200°C",
            "warranty": "2 years",
        },
        "keywords": ["air fryer", "havells", "budget", "digital", "cheap"],
    },
    # ── SMARTPHONES ──────────────────────────────────────────────────────────
    {
        "id": 13,
        "name": "Samsung Galaxy M34 5G",
        "brand": "Samsung",
        "category": "smartphones",
        "price": 16999,
        "currency": "INR",
        "rating": 4.3,
        "review_count": 67000,
        "image_url": "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0C84PZHVZ",
        "specs": {
            "processor": "Exynos 1280",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.5\" sAMOLED 120Hz",
            "battery": "6000mAh",
            "charging": "25W",
            "camera": "50MP triple",
            "os": "Android 14",
        },
        "keywords": ["phone", "samsung", "galaxy", "5g", "amoled", "6000mah", "budget"],
    },
    {
        "id": 14,
        "name": "Redmi Note 13 5G",
        "brand": "Xiaomi",
        "category": "smartphones",
        "price": 14999,
        "currency": "INR",
        "rating": 4.2,
        "review_count": 89000,
        "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0CRJKJZM1",
        "specs": {
            "processor": "Snapdragon 4 Gen 2",
            "ram": "8GB",
            "storage": "256GB",
            "display": "6.67\" AMOLED 120Hz",
            "battery": "5000mAh",
            "charging": "33W",
            "camera": "108MP triple",
            "os": "Android 13",
        },
        "keywords": ["phone", "redmi", "xiaomi", "108mp", "budget", "5g"],
    },
    {
        "id": 15,
        "name": "Realme Narzo 70 Pro",
        "brand": "Realme",
        "category": "smartphones",
        "price": 12999,
        "currency": "INR",
        "rating": 4.1,
        "review_count": 34000,
        "image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0CT69DLWQ",
        "specs": {
            "processor": "Dimensity 7050",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.67\" AMOLED 120Hz",
            "battery": "5000mAh",
            "charging": "67W",
            "camera": "50MP dual",
            "os": "Android 14",
        },
        "keywords": ["phone", "realme", "narzo", "budget", "fast charging", "67w"],
    },
    # ── SMARTWATCHES ─────────────────────────────────────────────────────────
    {
        "id": 16,
        "name": "Fire-Boltt Ninja Call Pro",
        "brand": "Fire-Boltt",
        "category": "smartwatches",
        "price": 1799,
        "currency": "INR",
        "rating": 3.9,
        "review_count": 112000,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0BXHXHD7T",
        "specs": {
            "display": "1.69\" TFT",
            "battery": "7 days",
            "bluetooth_calling": "Yes",
            "water_resistance": "IP67",
            "health_monitoring": "SpO2, Heart Rate, Sleep",
        },
        "keywords": ["smartwatch", "fire-boltt", "budget", "calling", "cheap", "ip67"],
    },
    {
        "id": 17,
        "name": "Portronics Kronos Y2",
        "brand": "Portronics",
        "category": "smartwatches",
        "price": 2499,
        "currency": "INR",
        "rating": 4.0,
        "review_count": 28000,
        "image_url": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0B2HGGN87",
        "specs": {
            "display": "1.85\" IPS",
            "battery": "7 days",
            "bluetooth_calling": "Yes",
            "water_resistance": "IP67",
            "health_monitoring": "SpO2, HR, Stress, Sleep",
        },
        "keywords": ["smartwatch", "portronics", "mid", "calling", "fitness"],
    },
    {
        "id": 18,
        "name": "Mi Smart Band 8",
        "brand": "Xiaomi",
        "category": "smartwatches",
        "price": 2999,
        "currency": "INR",
        "rating": 4.4,
        "review_count": 43000,
        "image_url": "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B0CDJD1FJY",
        "specs": {
            "display": "1.62\" AMOLED",
            "battery": "16 days",
            "water_resistance": "5ATM",
            "tracking": "SpO2, HR, Stress, 150 sports modes",
            "weight": "25g",
        },
        "keywords": ["fitness band", "mi", "xiaomi", "amoled", "16day battery", "slim"],
    },
    # ── APPLIANCES ───────────────────────────────────────────────────────────
    {
        "id": 19,
        "name": "Atomberg Efficio+ BLDC Fan",
        "brand": "Atomberg",
        "category": "appliances",
        "price": 2999,
        "currency": "INR",
        "rating": 4.5,
        "review_count": 31000,
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B08CW8JR6S",
        "specs": {
            "type": "Ceiling Fan BLDC",
            "wattage": "28W",
            "speed_settings": "5 (remote)",
            "star_rating": "5-star BEE",
            "warranty": "5 years",
            "blade_size": "1200mm",
        },
        "keywords": ["fan", "atomberg", "bldc", "energy saving", "remote", "5star"],
    },
    {
        "id": 20,
        "name": "Prestige PKSS 1.0 Electric Kettle",
        "brand": "Prestige",
        "category": "appliances",
        "price": 899,
        "currency": "INR",
        "rating": 4.2,
        "review_count": 18000,
        "image_url": "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=400&q=80",
        "product_url": "https://www.amazon.in/dp/B07FKMHH25",
        "specs": {
            "capacity": "1.5L",
            "wattage": "1500W",
            "auto_cutoff": "Yes",
            "body": "Stainless steel",
            "warranty": "1 year",
        },
        "keywords": ["kettle", "prestige", "electric kettle", "kitchen", "appliance", "budget"],
    },
]

# Mock default guest user profile for checkout
MOCK_USER_PROFILE = {
    "full_name": "Arjun Sharma",
    "address_line1": "42, Koramangala 4th Block",
    "address_line2": "",
    "city": "Bengaluru",
    "pincode": "560034",
    "phone": "9876543210",
    "default_payment": "card",
    "card_last4": "4242",
}
